import { resolve, relative, dirname, join } from "node:path"
import { readFileSync, writeFileSync, mkdirSync, readdirSync, type Dirent } from "node:fs"
import { parseTypesFromProject, toMock } from "../core/ast-to-mock"
import { serialize } from "../core/serialize"
import { getStringRanges, isInsideString } from "../core/string-utils"
import { collectEnumNames, buildEnumImports } from "../core/enum-utils"

export interface GenerateOptions {
  dir: string
  output: string
  exclude?: string[]
}

interface TypeUsage {
  singles: Set<string>         // createMock<T>()      → TMock
  lists:   Map<string, number> // createMockList<T>(n) → TMockList (max count per type)
}

const SKIP_DIRS    = ["node_modules", ".git", ".next", ".turbo", "dist", "out", "build", ".cache"]
const SKIP_PATTERN = /\.(test|spec|stories)\.[jt]sx?$|\.d\.ts$/

function walkFiles(dir: string, excludes: string[]): string[] {
  const results: string[] = []
  let entries: Dirent[]
  try { entries = readdirSync(dir, { withFileTypes: true }) } catch { return results }

  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (SKIP_DIRS.includes(entry.name) || excludes.includes(entry.name) || entry.name.startsWith(".")) continue
      results.push(...walkFiles(full, excludes))
    } else if (entry.isFile() && /\.[jt]sx?$/.test(entry.name) && !SKIP_PATTERN.test(entry.name)) {
      results.push(full)
    }
  }
  return results
}

function extractAllUsedTypes(source: string): TypeUsage {
  const singles = new Set<string>()
  const lists   = new Map<string, number>()
  const ranges  = getStringRanges(source)

  for (const m of source.matchAll(/createMock(?!List)<(\w+)>/g))
    if (!isInsideString(m.index!, ranges)) singles.add(m[1])

  for (const m of source.matchAll(/createMockList<(\w+)>\((\d+)/g)) {
    if (isInsideString(m.index!, ranges)) continue
    const typeName = m[1]
    const count    = parseInt(m[2], 10)
    lists.set(typeName, Math.max(lists.get(typeName) ?? 0, count))
  }

  return { singles, lists }
}

function extractUntransformedTypes(source: string): TypeUsage {
  const singles = new Set<string>()
  const lists   = new Map<string, number>()
  const ranges  = getStringRanges(source)

  for (const m of source.matchAll(/createMock(?!List)<(\w+)>\(\s*\)/g))
    if (!isInsideString(m.index!, ranges)) singles.add(m[1])

  for (const m of source.matchAll(/createMockList<(\w+)>\(\s*(\d+)\s*\)/g)) {
    if (isInsideString(m.index!, ranges)) continue
    const typeName = m[1]
    const count    = parseInt(m[2], 10)
    lists.set(typeName, Math.max(lists.get(typeName) ?? 0, count))
  }

  return { singles, lists }
}

function hasUntransformed(usage: TypeUsage): boolean {
  return usage.singles.size > 0 || usage.lists.size > 0
}

function mergeUsage(target: TypeUsage, source: TypeUsage): void {
  source.singles.forEach(t => target.singles.add(t))
  source.lists.forEach((count, t) =>
    target.lists.set(t, Math.max(target.lists.get(t) ?? 0, count))
  )
}

function addImport(source: string, stmt: string): string {
  if (source.includes(stmt)) return source

  const lines = source.split("\n")
  let lastImportLine = -1
  let inMultiline    = false

  for (let i = 0; i < lines.length; i++) {
    if (!inMultiline && /^import\b/.test(lines[i])) inMultiline = true
    if (inMultiline && / from ['"]/.test(lines[i])) {
      lastImportLine = i
      inMultiline    = false
    }
  }

  if (lastImportLine === -1) return stmt + "\n" + source
  lines.splice(lastImportLine + 1, 0, stmt)
  return lines.join("\n")
}

function transformSource(source: string, outputDir: string, fileDir: string): string {
  const ranges = getStringRanges(source)
  let out      = source

  out = out.replace(/createMock(?!List)<(\w+)>\(\s*\)/g, (match, typeName, offset) => {
    if (isInsideString(offset, ranges)) return match
    return `createMock<${typeName}>(mocks.${typeName}Mock)`
  })

  out = out.replace(/createMockList<(\w+)>\((\s*\d+\s*)\)/g, (match, typeName, count, offset) => {
    if (isInsideString(offset, ranges)) return match
    return `createMockList<${typeName}>(${count}, mocks.${typeName}MockList)`
  })

  if (out === source) return source

  const rel        = relative(fileDir, outputDir).replace(/\\/g, "/")
  const importPath = rel.startsWith(".") ? rel : "./" + rel
  out = addImport(out, `import * as mocks from "${importPath}"`)
  return out
}

function generateMocksFile(
  usage:     TypeUsage,
  state:     ReturnType<typeof parseTypesFromProject>,
  outputDir: string,
): void {
  const { typeMap, fileTypeMap, checker } = state
  const outputFile = join(outputDir, "index.ts")
  const lines: string[] = ["// Auto-generated by ts-mock. Do not edit.", ""]
  const allEnums = new Set<string>()
  const allTypes = new Set([...usage.singles, ...usage.lists.keys()])

  for (const typeName of allTypes) {
    try {
      if (usage.singles.has(typeName)) {
        const mock = toMock(typeName, typeMap, checker)
        collectEnumNames(mock, allEnums)
        lines.push(`export const ${typeName}Mock = ${serialize(mock, 0)}`)
      }
      if (usage.lists.has(typeName)) {
        const count    = usage.lists.get(typeName)!
        const mockList = Array.from({ length: count }, () => toMock(typeName, typeMap, checker))
        mockList.forEach(m => collectEnumNames(m, allEnums))
        lines.push(`export const ${typeName}MockList = ${serialize(mockList, 0)}`)
      }
      lines.push("")
    } catch (err) {
      console.warn(`[ts-mock] Cannot generate mock for ${typeName}: ${err instanceof Error ? err.message : err}`)
    }
  }

  const body        = lines.join("\n")
  const enumImports = buildEnumImports(outputFile, allEnums, fileTypeMap, body)
  const content     = enumImports ? enumImports + "\n\n" + body : body

  mkdirSync(outputDir, { recursive: true })
  writeFileSync(outputFile, content, "utf-8")
}

export async function generate(options: GenerateOptions): Promise<void> {
  const root      = resolve(options.dir)
  const outputDir = resolve(root, options.output)
  const excludes  = options.exclude ?? []

  console.log(`[ts-mock] Scanning ${root}...`)

  const state         = parseTypesFromProject(root, { excludeDirs: excludes })
  const outputRelName = relative(root, outputDir)
  const files         = walkFiles(root, [...excludes, outputRelName])

  const allUsage: TypeUsage = { singles: new Set(), lists: new Map() }
  const toTransform: Array<{ path: string; source: string }> = []

  for (const filePath of files) {
    const source = readFileSync(filePath, "utf-8")
    if (!source.includes("createMock")) continue

    mergeUsage(allUsage, extractAllUsedTypes(source))

    if (hasUntransformed(extractUntransformedTypes(source)))
      toTransform.push({ path: filePath, source })
  }

  if (allUsage.singles.size === 0 && allUsage.lists.size === 0) {
    console.log("[ts-mock] No createMock calls found.")
    return
  }

  generateMocksFile(allUsage, state, outputDir)
  console.log(`[ts-mock] Generated ${join(outputRelName, "index.ts")}`)

  let count = 0
  for (const { path: filePath, source } of toTransform) {
    const transformed = transformSource(source, outputDir, dirname(filePath))
    if (transformed !== source) {
      writeFileSync(filePath, transformed, "utf-8")
      console.log(`[ts-mock]   ✓ ${relative(root, filePath)}`)
      count++
    }
  }

  console.log(`[ts-mock] Done. ${count} file(s) transformed.`)
}
