// Auto-generated by ts-mock. Do not edit.

export const UserMock = {
  id: 89,
  name: "Dr. Lynette Feil",
  email: "Emmitt61@hotmail.com",
  phone: "(577) 385-8951 x21085",
  company: "Pouros - Aufderhar"
}
export const UserMockList = [
  {
    id: 47,
    name: "Amy Cartwright",
    email: "Tillman.Gibson@yahoo.com",
    phone: "(240) 559-4812 x0504",
    company: "O'Connell LLC"
  },
  {
    id: 100,
    name: "Diana Ankunding",
    email: "Reina_Johnston@hotmail.com",
    phone: "1-283-216-0130",
    company: "Lang, Monahan and Jenkins"
  },
  {
    id: 79,
    name: "Noel Kertzmann",
    email: "Wade_Rolfson@yahoo.com",
    phone: "1-315-527-7901",
    company: "Treutel Group"
  },
  {
    id: 47,
    name: "Jaime Heathcote",
    email: "Demarco.Morar@gmail.com",
    phone: "929.366.3852 x891",
    company: "Rau LLC"
  },
  {
    id: 87,
    name: "Regina Reynolds",
    email: "Harrison.Lang@gmail.com",
    phone: "458-723-7334 x566",
    company: "Fisher, Moore and Howell"
  }
]

export const PostMock = {
  id: 23,
  userId: 28,
  title: "sunt itaque ratione",
  body: "Adipisci omnis ipsam nesciunt et exercitationem nobis repudiandae corrupti. Atque eligendi omnis quo quos voluptates dolore iste perspiciatis. Magni ipsam sit mollitia saepe repellat pariatur. Labore modi repudiandae mollitia inventore."
}
export const PostMockList = [
  {
    id: 16,
    userId: 68,
    title: "est aliquam porro",
    body: "Quod eum exercitationem maxime repellat fugiat. Eum cumque laudantium aliquam ratione consectetur repudiandae. Amet deserunt beatae optio ratione. In nostrum explicabo provident."
  },
  {
    id: 20,
    userId: 64,
    title: "nobis sunt quidem",
    body: "Facilis modi amet. Labore mollitia sunt recusandae modi harum rem. Saepe inventore occaecati aperiam sunt odit vero similique id aspernatur. Optio tenetur assumenda non beatae quaerat harum ullam dolor. Cupiditate laudantium autem temporibus doloremque quo nisi ratione. Architecto quas inventore molestiae incidunt illum in quaerat corporis."
  },
  {
    id: 59,
    userId: 69,
    title: "molestiae nesciunt aspernatur",
    body: "Culpa facere debitis consequatur voluptate vero accusamus expedita animi. Culpa sequi quasi aliquid qui quisquam quis odit id officia. Necessitatibus maxime quod doloremque dolor placeat fuga. Consequuntur deserunt similique vero omnis."
  },
  {
    id: 97,
    userId: 85,
    title: "iusto unde necessitatibus",
    body: "Eligendi est quibusdam. Reiciendis culpa expedita ducimus facilis libero nesciunt. Soluta illum perferendis deleniti similique placeat commodi quo dolores. Doloremque aspernatur neque quod consectetur eum ducimus. Facilis deserunt mollitia praesentium quae earum. Amet doloremque neque quisquam dolores."
  },
  {
    id: 95,
    userId: 32,
    title: "inventore tenetur eum",
    body: "Reprehenderit architecto vitae. Minima provident recusandae quibusdam repellat deserunt iste eum error suscipit. Quaerat ullam officiis perferendis in est."
  }
]

export const ProductMock = {
  id: 41,
  name: "Moses Crona",
  price: 44,
  description: "Facilis accusamus amet quasi ad ut.",
  category: "possimus"
}
export const ProductMockList = [
  {
    id: 56,
    name: "Iris Cormier",
    price: 38,
    description: "Ipsam possimus adipisci adipisci.",
    category: "expedita"
  },
  {
    id: 37,
    name: "Gregory Murray",
    price: 11,
    description: "Hic vero accusamus voluptatum.",
    category: "magni"
  },
  {
    id: 53,
    name: "Matthew Streich",
    price: 12,
    description: "Unde dicta explicabo vero beatae.",
    category: "in"
  },
  {
    id: 73,
    name: "Shawn D'Amore",
    price: 37,
    description: "Excepturi itaque cupiditate voluptas saepe.",
    category: "reiciendis"
  },
  {
    id: 68,
    name: "Cesar Harvey",
    price: 27,
    description: "Cumque officiis animi totam id molestiae repudiandae.",
    category: "molestias"
  }
]

export const OrderMock = {
  id: 0,
  userId: 9,
  productId: 95,
  quantity: 70,
  status: "cum",
  createdAt: "2026-06-06T14:44:29.086Z"
}
export const OrderMockList = [
  {
    id: 6,
    userId: 28,
    productId: 31,
    quantity: 1,
    status: "laboriosam",
    createdAt: "2026-06-06T17:13:38.457Z"
  },
  {
    id: 100,
    userId: 90,
    productId: 63,
    quantity: 11,
    status: "eveniet",
    createdAt: "2026-06-06T22:58:54.947Z"
  },
  {
    id: 81,
    userId: 58,
    productId: 84,
    quantity: 34,
    status: "ratione",
    createdAt: "2026-06-07T12:51:06.771Z"
  },
  {
    id: 10,
    userId: 12,
    productId: 79,
    quantity: 16,
    status: "repellendus",
    createdAt: "2026-06-07T05:55:46.047Z"
  },
  {
    id: 75,
    userId: 13,
    productId: 69,
    quantity: 82,
    status: "eveniet",
    createdAt: "2026-06-07T03:02:38.215Z"
  }
]

export const CommentMock = {
  id: 51,
  postId: 98,
  name: "Shane Ritchie",
  email: "Audrey64@gmail.com",
  body: "Nostrum officiis rerum labore ut vero quidem nulla non. Quos corporis tempore nostrum omnis rem modi praesentium. Beatae dicta perferendis temporibus rerum inventore labore assumenda. Vitae aliquam assumenda pariatur officiis sed minus voluptas. Molestiae animi magnam porro error veniam optio inventore."
}
export const CommentMockList = [
  {
    id: 40,
    postId: 85,
    name: "Eric Schultz",
    email: "Pasquale26@gmail.com",
    body: "Porro fugit amet. Dolor corporis dolorum at voluptas expedita. Perspiciatis aliquid consectetur quia mollitia officia dolores nemo similique."
  },
  {
    id: 39,
    postId: 26,
    name: "Mr. Rosemarie Rodriguez IV",
    email: "Una.Purdy85@gmail.com",
    body: "Perferendis iusto at reprehenderit dolores debitis unde neque hic incidunt. Iste qui praesentium et tenetur. Eos est nam earum saepe corporis officiis. Nam expedita culpa. Optio quas voluptates cumque animi earum ducimus."
  },
  {
    id: 54,
    postId: 35,
    name: "Barbara Rath",
    email: "Petra.Kohler@gmail.com",
    body: "Facere delectus placeat delectus eligendi ratione officiis. Temporibus magnam molestias incidunt beatae fugit vitae laboriosam eum. Neque inventore nostrum quam corrupti. Ad ipsam exercitationem iure voluptatem. Laudantium reiciendis illo."
  },
  {
    id: 78,
    postId: 98,
    name: "Ann Schmitt PhD",
    email: "Daphney97@yahoo.com",
    body: "Aliquam voluptates mollitia. Repudiandae ullam hic aspernatur dolor maxime quibusdam nisi totam. Deserunt sit occaecati velit aperiam reprehenderit sed mollitia pariatur. Ullam voluptatibus ad quos nostrum voluptatum. Sapiente aliquam ducimus mollitia nihil porro. Vel aut quasi cumque architecto quo."
  },
  {
    id: 19,
    postId: 67,
    name: "Dr. Philip Cronin",
    email: "Corbin97@gmail.com",
    body: "Eaque inventore architecto ducimus quisquam sed. Laudantium eum in voluptatem illum eum hic perferendis dolorum. Quisquam sint earum nisi. Illum iusto fugit corporis optio inventore reprehenderit. Impedit aliquam architecto sunt molestias velit tempora."
  }
]
