// Auto-generated by ts-mock. Do not edit.

export const UserMock = {
  id: 64,
  name: "Lorenzo Gutkowski IV",
  email: "Cortney_Graham@gmail.com",
  phone: "824-800-6360",
  company: "Pagac Inc"
}
export const UserMockList = [
  {
    id: 61,
    name: "Kimberly Lehner",
    email: "Jamaal.Wyman@gmail.com",
    phone: "598-633-8531 x818",
    company: "Collins - Lesch"
  }
]

export const PostMock = {
  id: 23,
  userId: 82,
  title: "nam totam impedit",
  body: "Repellendus laborum ratione provident qui nobis ex. Nisi aut excepturi eveniet eos provident deleniti ratione provident. Exercitationem molestias doloremque quos. Velit voluptatibus minima architecto esse unde dolore. Nostrum quae provident voluptatum molestiae fugit assumenda quae ipsa distinctio. Beatae tenetur excepturi."
}
export const PostMockList = [
  {
    id: 53,
    userId: 9,
    title: "officiis debitis ea",
    body: "Natus temporibus eos. Architecto ut excepturi eligendi magnam in aspernatur nisi. Quidem similique eum mollitia. Architecto laboriosam occaecati aliquid fuga minima numquam iste optio."
  },
  {
    id: 64,
    userId: 9,
    title: "aliquid exercitationem quas",
    body: "Laborum excepturi labore reiciendis atque voluptates quasi quasi vel. Veritatis aliquid necessitatibus eius. Ipsum incidunt numquam ipsum eveniet similique nesciunt exercitationem esse. Eum hic minus aliquid molestias tempore unde officiis."
  },
  {
    id: 39,
    userId: 44,
    title: "animi ab beatae",
    body: "Perspiciatis hic cumque optio. Dolore aperiam eius ipsa autem laudantium explicabo molestiae saepe non. Ab consequatur autem. Magnam eius quos id."
  },
  {
    id: 41,
    userId: 39,
    title: "odit placeat aliquid",
    body: "Eos at cum veritatis. Occaecati explicabo deleniti fuga impedit. Debitis totam saepe quam velit est accusantium ratione autem. Sint quisquam consequatur cum fuga voluptatum veritatis eum odio. Expedita cumque rerum inventore error."
  },
  {
    id: 15,
    userId: 72,
    title: "sed sit asperiores",
    body: "Libero sint sapiente vitae voluptate. Sunt voluptatibus saepe quisquam possimus totam incidunt. Fuga rem sunt minima voluptatum soluta distinctio ipsam earum non."
  }
]

export const ProductMock = {
  id: 59,
  name: "Craig Oberbrunner",
  price: 16,
  description: "Fugiat eligendi qui nemo corrupti.",
  category: "hic"
}
export const ProductMockList = [
  {
    id: 20,
    name: "Kelly Barrows",
    price: 56,
    description: "Necessitatibus culpa tenetur similique voluptatem debitis tempore ipsa quaerat.",
    category: "praesentium"
  },
  {
    id: 15,
    name: "Jo Gusikowski Jr.",
    price: 27,
    description: "Dicta corporis amet.",
    category: "deserunt"
  },
  {
    id: 6,
    name: "Marie Carter",
    price: 25,
    description: "Dolorum dolorem ullam iste veniam optio numquam a.",
    category: "adipisci"
  },
  {
    id: 86,
    name: "Kelli Little",
    price: 34,
    description: "Magnam qui commodi placeat nesciunt.",
    category: "expedita"
  },
  {
    id: 29,
    name: "Kelli Padberg",
    price: 57,
    description: "Numquam ex magnam laboriosam molestias ut ducimus praesentium.",
    category: "et"
  }
]

export const OrderMock = {
  id: 22,
  userId: 60,
  productId: 69,
  quantity: 23,
  status: "voluptatem",
  createdAt: "2026-06-06T19:46:05.797Z"
}
export const OrderMockList = [
  {
    id: 7,
    userId: 64,
    productId: 49,
    quantity: 9,
    status: "possimus",
    createdAt: "2026-06-07T07:26:26.980Z"
  },
  {
    id: 63,
    userId: 82,
    productId: 18,
    quantity: 75,
    status: "eveniet",
    createdAt: "2026-06-07T06:10:54.946Z"
  },
  {
    id: 53,
    userId: 47,
    productId: 48,
    quantity: 30,
    status: "modi",
    createdAt: "2026-06-07T10:59:04.008Z"
  },
  {
    id: 82,
    userId: 13,
    productId: 49,
    quantity: 76,
    status: "aspernatur",
    createdAt: "2026-06-07T07:25:50.141Z"
  },
  {
    id: 53,
    userId: 95,
    productId: 11,
    quantity: 77,
    status: "sapiente",
    createdAt: "2026-06-06T20:47:56.973Z"
  }
]

export const CommentMock = {
  id: 25,
  postId: 68,
  name: "Miss Loren Moore",
  email: "Bobby19@gmail.com",
  body: "Aut asperiores necessitatibus laboriosam dolores. Voluptatem reiciendis perferendis illum. Quia distinctio impedit quos natus eaque. Sunt odit animi dignissimos. Fugit illo laudantium. Magnam accusamus eveniet."
}
export const CommentMockList = [
  {
    id: 4,
    postId: 96,
    name: "Matt Graham",
    email: "Jedidiah_Cummerata53@hotmail.com",
    body: "Quibusdam iste pariatur quaerat recusandae modi numquam labore magnam. Ullam nemo occaecati nihil voluptatibus excepturi hic laboriosam. Nobis pariatur a iste."
  },
  {
    id: 94,
    postId: 88,
    name: "Ismael Reilly DDS",
    email: "Kristin3@yahoo.com",
    body: "Fugit velit architecto quae aut. Voluptates unde beatae facilis impedit quo ab mollitia nostrum modi. Ipsa voluptatem tempore quis delectus. Laborum consequuntur animi officiis nesciunt. Consectetur distinctio tempore quibusdam non."
  },
  {
    id: 52,
    postId: 52,
    name: "Jessie Prohaska",
    email: "Candace31@yahoo.com",
    body: "Saepe nam odio pariatur ex dignissimos. Consequatur dolorem similique quidem itaque veniam at provident. Beatae velit alias praesentium."
  },
  {
    id: 47,
    postId: 81,
    name: "Miriam Casper",
    email: "Jodie.Armstrong@gmail.com",
    body: "Asperiores cumque delectus laborum dolorem dolorum rem deserunt. Voluptates accusamus rem maxime voluptate. Veniam deserunt accusantium et magni molestiae esse. Consequuntur necessitatibus consequatur dolorum fugit odit facere placeat inventore. Recusandae accusantium repellendus quibusdam odio accusantium qui alias quis. Dicta animi asperiores nostrum harum eveniet sint velit."
  },
  {
    id: 52,
    postId: 29,
    name: "Ryan Frami",
    email: "Zora_Kemmer@yahoo.com",
    body: "Voluptatum fugiat corrupti possimus nostrum exercitationem. Sequi eaque exercitationem. Distinctio nesciunt ipsa asperiores cupiditate aliquid tenetur illo accusantium consectetur. Iusto vero laudantium. Consequatur asperiores dolor. Quam quaerat harum magnam laboriosam."
  }
]
